# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stats_window(object):
    def setupUi(self, stats_window):
        stats_window.setObjectName("stats_window")
        stats_window.resize(190, 270)
        stats_window.setMinimumSize(QtCore.QSize(190, 270))
        stats_window.setMaximumSize(QtCore.QSize(190, 270))
        self.leave = QtWidgets.QPushButton(stats_window)
        self.leave.setGeometry(QtCore.QRect(10, 220, 171, 41))
        self.leave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leave.setObjectName("leave")
        self.name = QtWidgets.QLabel(stats_window)
        self.name.setGeometry(QtCore.QRect(10, 0, 81, 31))
        self.name.setMinimumSize(QtCore.QSize(81, 31))
        self.name.setMaximumSize(QtCore.QSize(81, 31))
        self.name.setObjectName("name")
        self.adress_number = QtWidgets.QLabel(stats_window)
        self.adress_number.setGeometry(QtCore.QRect(100, 0, 81, 31))
        self.adress_number.setMinimumSize(QtCore.QSize(81, 31))
        self.adress_number.setMaximumSize(QtCore.QSize(81, 31))
        self.adress_number.setObjectName("adress_number")
        self.scrollArea = QtWidgets.QScrollArea(stats_window)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 171, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(stats_window)
        QtCore.QMetaObject.connectSlotsByName(stats_window)

    def retranslateUi(self, stats_window):
        _translate = QtCore.QCoreApplication.translate
        stats_window.setWindowTitle(_translate("stats_window", "Statystyki"))
        self.leave.setText(_translate("stats_window", "Wyjdź"))
        self.name.setText(_translate("stats_window", "Imię"))
        self.adress_number.setText(_translate("stats_window", "Ilość adresów"))
